services:
  web:
    build: .
    container_name: Water_Report_API_New
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      DEBUG: "True"
      POSTGRES_DB: water_db
      POSTGRES_USER: water_user
      POSTGRES_PASSWORD: water_password
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: Water_Report_DB_New
    restart: always
    environment:
      POSTGRES_DB: water_db
      POSTGRES_USER: water_user
      POSTGRES_PASSWORD: water_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new: