# Generated by Django 6.0.6 on 2026-06-27 03:16

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFuga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_incidente', models.CharField(choices=[('BANQUETA', 'Fuga en banqueta / vía pública'), ('MEDIDOR', 'Fuga en el medidor'), ('DRENAJE', 'Brote de aguas negras'), ('OTRO', 'Otro tipo de reporte')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api.models.ruta_foto_fuga)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRESO', 'En atención'), ('RESUELTO', 'Solucionado')], default='PENDIENTE', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_fugas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
