"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = 'django-insecure-sk!+%1eyd^_vgzju8yd1&tyk#yf(+x==u5y7mp%b7g*7+7srra'

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "172.27.153.209",
    "*", 
]

# Orígenes permitidos para hacer peticiones HTTP/Fetch desde el Frontend
#CORS_ALLOWED_ORIGINS = [
 #   "http://localhost",
  #  "http://localhost:8080",      # XAMPP
   # "http://127.0.0.1:8080",
    #"http://localhost:5500",      #Live Server en VS Code
    #"http://127.0.0.1:5500",
#]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework_simplejwt',
    'rest_framework',
    'rest_framework.authtoken', 
    'corsheaders',
    
    
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'




#DATABASES = {
   # 'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #
   #     'NAME': BASE_DIR / 'db.sqlite3',
  #  }
#}



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'water_db'),
        'USER': os.environ.get('POSTGRES_USER', 'water_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'water_password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Tijuana'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =========================================
# CONFIGURACIÓN DE AUTENTICACIÓN Y API
# =========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================
# CORS
# =========================================

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True


# =========================================
# DJANGO REST FRAMEWORK
# =========================================

REST_FRAMEWORK = {

    # Autenticación
    'DEFAULT_AUTHENTICATION_CLASSES': (

        # JWT utilizado por el login administrativo
        'rest_framework_simplejwt.authentication.JWTAuthentication',

        # Autenticación básica de DRF
        'rest_framework.authentication.BasicAuthentication',

        # Token Authentication
        'rest_framework.authentication.TokenAuthentication',

        # Sesiones de Django / DRF
        'rest_framework.authentication.SessionAuthentication',

    ),

    # Permisos
    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticatedOrReadOnly',

    ),

    # Renderizadores
    'DEFAULT_RENDERER_CLASSES': [

        'rest_framework.renderers.JSONRenderer',

        'rest_framework.renderers.BrowsableAPIRenderer',

    ],

    # Parsers
    'DEFAULT_PARSER_CLASSES': [

        'rest_framework.parsers.JSONParser',

        'rest_framework.parsers.FormParser',

        'rest_framework.parsers.MultiPartParser',

    ],

    # Paginacion
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE':
        50,

    # Filtros
    'DEFAULT_FILTER_BACKENDS': [

        'rest_framework.filters.SearchFilter',

        'rest_framework.filters.OrderingFilter',

    ],

}